local _, ns = ...
local C = ns.C

C["MACRO_EDITOR"] = {}
C["MACRO_EDITOR"]["NUM_MACRO_CATEGORIES"] = 12
C["MACRO_EDITOR"]["NUM_MACRO_COMMANDS"] = 32
C["MACRO_EDITOR"]["MAX_ARGUMENTS"] = 3
C["MACRO_EDITOR"]["MAX_CONDITIONAL_GROUPS"] = 5
C["MACRO_EDITOR"]["HASH_CATEGORY"] = "Metacommands"
C["MACRO_EDITOR"]["BASE_WIDTH"] = 312
C["MACRO_EDITOR"]["BASE_LINE_POPUP_HEIGHT"] = 144
C["MACRO_EDITOR"]["BASE_ARGUMENT_POPUP_HEIGHT"] = 122